# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Chalk"
license = "MIT"
licenselink = "https://github.com/ph-ph/chalk/blob/master/LICENSE"
description = "A simple, clean, flexible Hugo theme"
homepage = "https://github.com/ph-ph/chalk/"
tags = ["Responsive", "Simple", "Clean", "Light", "White", "Blog"]
features = ["Responsive", "One Column", "Blog"]
min_version = "0.57.1"

[author]
  name = "ph-ph"
  homepage = "https://blog.dkishylau.com/"

[original]
  author = "nielsenramon"
  repo = "https://github.com/nielsenramon/chalk"
